-- Add news_item_url columns to HS_CONTENT_TB table
ALTER TABLE HS_CONTENT_TB ADD COLUMN news_item_url_1 VARCHAR(500);
ALTER TABLE HS_CONTENT_TB ADD COLUMN news_item_url_2 VARCHAR(500);
ALTER TABLE HS_CONTENT_TB ADD COLUMN news_item_url_3 VARCHAR(500);